apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_DATABASE: YWNjb3VudHM=
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: cGFzc3dvcmQ=


